FROM node:14

#Create a directory to hold the application code inside the image, this will be the working directory for your application:
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3001

CMD [ "node", "index.js" ]